import React, { Component } from "react";
import BioParts from "./parts";

import "./build.css";

class Build extends Component {
  render() {
    return (
      <div className="eng-build">
        <div className="build-title">Build</div>
        <div className="build-section">
          <div className="bld-sect-title">Circuit Design</div>
          <div className="bld-sect-contnt">
            <div className="bld-img">
              <img
                src={process.env.PUBLIC_URL + "/team/Marcelo.jpeg"}
                alt=""
                width="90%"
              />
            </div>
            <div className="bld-txt">
              <div>
                RBD (PDB: 6M0J), RTB (PDB ID: S40366) and MBP (PDB ID: 1ELJ)
                sequences were obtained from Protein Data Bank (PDB:
                <a href="https://www.rcsb.org/">https://www.rcsb.org/</a>). To
                design a chimeric protein containing the RBD domain and RTB
                region, the amino acids from 319–541 from SARS-Cov-2 Spike
                protein and amino acids from 1209–1997 from Ricin were selected,
                respectively. These fragments were linked together via a
                GGGSGGGSGGGS linker. The latter was also used to join RBD and
                MBP domains.
              </div>
            </div>
          </div>
        </div>
        <div className="build-section">
          <div className="bld-sect-title">Genetic Engineering Strategy</div>
          <div className="bld-sect-contnt">
            <div className="bld-txt">
              <div>
                <div className="bld-par">
                  RTB region was flanked by NcoI and SalI restriction sites and
                  MBP domain, the linker by SalI and NcoI, and RBD region by
                  NcoI and SacI sites. This strategy allows generating all the
                  desired constructs from the three biobricks using only three
                  restriction enzymes. First, we already have two control
                  groups: only RTB and MBP. Only the RBD region was generated
                  using the NcoI enzyme. RTB/RBD and MBP/RBD groups were
                  obtained through the sticky ends generated by SalI restriction
                  enzymes.
                </div>
                <div className="bld-par">
                  Our genetic parts have been designed to fulfill requirements
                  from the Registry of Standard Biological Parts. The design on
                  Benchling allows them to be standard with RFC10 and TypellS.
                </div>
              </div>
            </div>
            <div className="bld-img">
              <img
                src={process.env.PUBLIC_URL + "/engineering/genetic.png"}
                alt=""
                width="90%"
              />
            </div>
          </div>
        </div>
        <div className="build-section">
          <BioParts />
        </div>
        <div className="build-section">
          <div className="sect-ctrlcases">
            <div className="ctrlcases-title">
              Control cases in the cloning plasmid pGEM-T Easy
            </div>
            <div className="ctrlcases-img">
              <img
                src={process.env.PUBLIC_URL + "/engineering/genetic.png"}
                alt=""
                width="400px"
              />
              <img
                src={process.env.PUBLIC_URL + "/engineering/genetic.png"}
                alt=""
                width="400px"
              />
              <img
                src={process.env.PUBLIC_URL + "/engineering/genetic.png"}
                alt=""
                width="400px"
              />
            </div>
          </div>
          <div className="sect-ctrlcases">
            <div className="ctrlcases-img">
              <img
                src={process.env.PUBLIC_URL + "/engineering/genetic.png"}
                alt=""
                width="400px"
              />
              <img
                src={process.env.PUBLIC_URL + "/engineering/genetic.png"}
                alt=""
                width="400px"
              />
              <img
                src={process.env.PUBLIC_URL + "/engineering/genetic.png"}
                alt=""
                width="400px"
              />
            </div>
            <div className="ctrlcases-title">
              Control cases in the expression plasmid pET-28 (b) +
            </div>
          </div>
          <div className="sect-ctrlcases">
            <div className="ctrlcases-title">
              Treatment 1 - pGEM-T Easy and pET-28 (b) +
            </div>
            <div className="ctrlcases-img">
              <img
                src={process.env.PUBLIC_URL + "/engineering/genetic.png"}
                alt=""
                width="400px"
              />
              <img
                src={process.env.PUBLIC_URL + "/engineering/genetic.png"}
                alt=""
                width="400px"
              />
            </div>
          </div>
          <div className="sect-ctrlcases">
            <div className="ctrlcases-img">
              <img
                src={process.env.PUBLIC_URL + "/engineering/genetic.png"}
                alt=""
                width="400px"
              />
              <img
                src={process.env.PUBLIC_URL + "/engineering/genetic.png"}
                alt=""
                width="400px"
              />
            </div>
            <div className="ctrlcases-title">
              Treatment 2 - pGEM-T Easy and pET-28 (b) +
            </div>
          </div>
        </div>
      </div>
    );
  }
}

export default Build;
